/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Marketing;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Business.Business;
import model.ProductManagement.Product;
import model.Supplier.Supplier;
import model.UserAccountManagement.UserAccount;

/**
 *
 * @author anupbochare
 */
public class UpdateTargetPriceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateTargetPriceJPanel
     */
    JPanel cardSequencePanel;
    Business business;
    UserAccount userAccount;

    public UpdateTargetPriceJPanel(JPanel cardSequencePanel, Business business, UserAccount userAccount) {
        initComponents();
        this.cardSequencePanel = cardSequencePanel;
        this.business = business;
        this.userAccount = userAccount;
        populateSupplier();
    }

    private void populateSupplier() {
        business.getSupplierDirectory().getSupplierList().forEach(supplier -> {
            cmbSupplier.addItem(supplier);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProductCatalogue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductComparison = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        lblSupplier = new javax.swing.JLabel();
        cmbSupplier = new javax.swing.JComboBox();
        txtNewQuantity = new javax.swing.JTextField();
        btnModifyTargetPrice = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));

        lblProductCatalogue.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblProductCatalogue.setForeground(new java.awt.Color(255, 255, 255));
        lblProductCatalogue.setText("Product Catalog:");

        tblProductComparison.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        tblProductComparison.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Floor Price", "Ceiling Price", "Target Price", "Recommended Price", "Product Comparison"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProductComparison);

        btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblSupplier.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblSupplier.setForeground(new java.awt.Color(255, 255, 255));
        lblSupplier.setText("Supplier :");

        cmbSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSupplierActionPerformed(evt);
            }
        });

        txtNewQuantity.setForeground(new java.awt.Color(255, 255, 255));

        btnModifyTargetPrice.setBackground(new java.awt.Color(204, 0, 0));
        btnModifyTargetPrice.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnModifyTargetPrice.setText("Modify Target");
        btnModifyTargetPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyTargetPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnModifyTargetPrice)
                            .addGap(18, 18, 18)
                            .addComponent(txtNewQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblProductCatalogue)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(lblProductCatalogue)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModifyTargetPrice)
                    .addComponent(txtNewQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        cardSequencePanel.remove(this);
        CardLayout layout = (CardLayout) cardSequencePanel.getLayout();
        layout.previous(cardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSupplierActionPerformed
        // TODO add your handling code here:
        populateProducts();
    }//GEN-LAST:event_cmbSupplierActionPerformed
    private void populateProducts() {
        int selectedSupplierIndex = cmbSupplier.getSelectedIndex();
        if (selectedSupplierIndex < 0) {
            return;
        }
        DefaultTableModel dtm = (DefaultTableModel) tblProductComparison.getModel();
        dtm.setRowCount(0);
        Supplier selectedSupplier = (Supplier) cmbSupplier.getSelectedItem();
        for (int i = 0; i < selectedSupplier.getProductCatalog().getProductList().size(); i++) {
            Object row[] = new Object[6];
            row[0] = selectedSupplier.getProductCatalog().getProductList().get(i);
            row[1] = selectedSupplier.getProductCatalog().getProductList().get(i).getFloorPrice();
            row[2] = selectedSupplier.getProductCatalog().getProductList().get(i).getCeilingPrice();
            row[3] = selectedSupplier.getProductCatalog().getProductList().get(i).getTargetPrice();
            row[4] = selectedSupplier.getProductCatalog().getProductList().get(i).getRecommendedPrice();
            row[5] = getAveragePrice(selectedSupplier, i);
            dtm.addRow(row);
        }
    }

    public int getAveragePrice(Supplier selectedSupplier, Integer rowCount) {
        int sumOfPrice = 0;
        for (Supplier supplier : business.getSupplierDirectory().getSupplierList()) {
            if (!supplier.equals(selectedSupplier)) {
                sumOfPrice += supplier.getProductCatalog().getProductList().get(rowCount).getTargetPrice();
            }
        }
        return sumOfPrice / (business.getSupplierDirectory().getSupplierList().size() - 1);
    }
    private void btnModifyTargetPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyTargetPriceActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblProductComparison.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select an item from the cart", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Product product = (Product) tblProductComparison.getValueAt(selectedRow, 0);
        int newQuantity;
        try {
            newQuantity = Integer.parseInt(txtNewQuantity.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid quantity", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (newQuantity <= 0) {
            JOptionPane.showMessageDialog(null, "Quantity should be greater than 0", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        product.updateProduct(product.getFloorPrice(), product.getCeilingPrice(), newQuantity);
        populateProducts();
    }//GEN-LAST:event_btnModifyTargetPriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnModifyTargetPrice;
    private javax.swing.JComboBox cmbSupplier;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProductCatalogue;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JTable tblProductComparison;
    private javax.swing.JTextField txtNewQuantity;
    // End of variables declaration//GEN-END:variables
}
